### ISSUE TITLE
Query language: allow search for not existent tags

### ISSUE THREAD

**Issue by saerdnaer** [drolbr/Overpass-API#132]
If I want to search all buildings with an house number, but no addr:street Tag I currently have use following workaround `<has-kv k="addr:street" modv="not" regv="."/>`.

 I think a own language option like  `<has-kv modk="not" k="addr:street" />` or `<has-not-k k="addr:street" />` would be much better. The proposed Overpass QL variant would be `node[!"addr:street"];`

**Comment by mmd-osm** [comment]
@saerdnaer : Preliminary patch is out now for testing. I didn't bother to implement an Overpass XML counterpart at this time, as I don't see a real need for it. 

* http://overpass-turbo.eu/s/c5H
* http://overpass-turbo.eu/s/c5I

Please give it a try and report back issues or regressions you may encounter.

This patch is really syntactic sugar only, as it simply translates `[!key]` into `[key!~"."]` before running the query. This way, the patch shouldn't introduce too many side effects.

Automated test case is still missing. I guess I need support from @drolbr as always for the test suite.

 Feedback from power users in the community would also be appreciated. @tyrasd

**Comment by tyrasd** [comment]
I'm definitely :+1: for a dedicated no-tag-operator, because the regex variant is a very frequently used "hack" and users would surely benefit from a better readable syntax. It would also open the path to a future speed-optimization of this particular query type, if that would be needed at some point.

btw: the _any value_ regex (that would be used internally) should read `.*`, not just `.` as the latter doesn't work in the case where a tag with the given key is present on an object, but has an empty value.

**Comment by mmd-osm** [comment]
@tyrasd : thanks for the `.*` reminder, I tend to forget about those empty values! Patch is corrected and new version deployed now.
