### ISSUE TITLE
Objects not ordered by ID in augmented diffs

### ISSUE THREAD

**Issue by rurseekatze** [drolbr/Overpass-API#139]
The objects returned in augmented diffs are sometimes not ordered correctly by id. This causes problems in other programs like osmconvert.

Example from http://overpass-api.de/api/augmented_diff?id=1074425:

```
<action type="create">
  <node id="3100103234" lat="50.9818131" lon="2.7417284" version="1" timestamp="2014-09-28T10:00:45Z" changeset="25721881" uid="138772" user="lodde1949"/>
</action>
<action type="create">
  <node id="3100103235" lat="50.9820852" lon="2.7417312" version="1" timestamp="2014-09-28T10:00:45Z" changeset="25721881" uid="138772" user="lodde1949"/>
</action>
<action type="modify">
<old>
  <node id="505319784" lat="50.9802016" lon="2.7415668" version="6" timestamp="2011-09-15T14:34:09Z" changeset="9308608" uid="15188" user="Polyglot">
    <tag k="rcn_ref" v="56"/>
  </node>
</old>
<new>
  <node id="505319784" lat="50.9802138" lon="2.7415557" version="7" timestamp="2014-09-28T10:00:54Z" changeset="25721881" uid="138772" user="lodde1949">
    <tag k="rcn_ref" v="56"/>
  </node>
</new>
</action>
<action type="create">
  <node id="3100102920" lat="50.9720431" lon="2.7231863" version="1" timestamp="2014-09-28T10:00:39Z" changeset="25721881" uid="138772" user="lodde1949"/>
</action>
```

**Comment by rurseekatze** [comment]
We decided to continue with our current processing toolchain and not to move to Overpass API because the data returned by Overpass API was missing some essential things:

To be able to process the data with other tools and update our database, it would be necessary that the adiff also contains the nodes, not just the coordinates of the nodes as a part of the ways. But as @drolbr told me, returning the complete node objects caused too much load on the server and too big diffs, so he removed this feature.

**Comment by mmd-osm** [comment]
> To be able to process the data with other tools and update our database, it would be necessary that the adiff also contains the nodes, not just the coordinates of the nodes as a part of the ways.

That's just the way the [augmented_diff script](https://github.com/drolbr/Overpass-API/blob/master/src/cgi-bin/augmented_diff) produces its output, in this case via `out meta geom;`. However, there's no technical reason to stick to this format, when you run your own QL query instead. I guess the format you were looking for is somewhat similar to this one: http://overpass-turbo.eu/s/cZI
Instead of returning all changes in a timeframe, it just returns changes to `railway` tags. That should also limit the amount of data, which is returned by that query.
