### ISSUE TITLE
Another request from your IP is still running

### ISSUE THREAD

**Issue by TheFive** [drolbr/Overpass-API#223]
I have serialized my requests to Overpass and to have implemented (experimental) a wait time, that varies between 100 ms and 2 seconds, depending of the number of errors or successful queries, my program receives.

But still get the message: Another request from your IP is still running.
As a reaction my program kills all queries from my IP immediate. 
The reaction of overpass is always: 
No query running from IP.

Whats the reason for this behavior ? As long as kill_all_queries just results in There is no Query running, i expect no mistake in my code.

Christoph

**Comment by mmd-osm** [comment]
I see two issues here:

1) The error message "Another request from your IP is still running" is somewhat misleading. It was originally used for a query, which had to wait for more than 15 seconds to get executed (in which case it would be aborted). Since 0.7.52 there's an additional meaning for the same error message: a too high number of requests in a 15 minute interval. I recommend to simply ignore the text of this error message as it is today. It needs some rework to describe the real reason.

See  https://github.com/drolbr/Overpass-API/blob/master/src/overpass_api/dispatch/web_query.cc#L175 for details. 

2) `kill_my_queries` has currently no impact at all, see #214

**Comment by drolbr** [comment]
The messages resulting from the different quota mechanisms are indeed misleading. Hence this is classified as bug.

**Comment by drolbr** [comment]
The message has been rephrased in commit 7cc9e47fdcb093e6c9a5fc6bd043e853f694449d
