### ISSUE TITLE
Return <bounds> in XML format

### ISSUE THREAD

**Issue by simon04** [drolbr/Overpass-API#251]
The OSM API returns a `<bounds>` element in its XML response. This is used in editors as JOSM to display the downloaded area.

When a file downloaded w/ Overpass API is opened in JOSM, or the remote control is used to perform an Overpass API query, JOSM cannot determine the bounds and shows bounds of the world, which is confusing.

Please also return a `<bounds>` element when `[out:xml]` is used.

----

For example, https://api.openstreetmap.org/api/0.6/map?bbox=6.3254411,51.0578729,6.3275347,51.0611313  returns
```xml
<osm version="0.6" generator="CGImap 0.4.0 (22133 thorn-03.openstreetmap.org)" copyright="OpenStreetMap and contributors" attribution="http://www.openstreetmap.org/copyright" license="http://opendatacommons.org/licenses/odbl/1-0/">
 <bounds minlat="51.0578729" minlon="6.3254411" maxlat="51.0611313" maxlon="6.3275347"/>
<!-- ... -->
</osm>
```

**Comment by mmd-osm** [comment]
That really depends on your query. If you're using a global bbox setting, you will already get a `<bounds>` tag today, even in XML mode. Please try this example:

```C
[bbox:{{bbox}}];
node[highway=turning_circle];
out;

```

In other cases, where no global bbox is set, I would assume that this is **impossible by design**. You don't really know upfront, where the data is coming from (when you start printing the results - it may be even global). That all depends on each individual query + *out* statement. To make that happen, you would need to evaluate the whole query first, store the results temporarily, determine the bbox and only then start printing the results including a bbox. This has been rejected by Roland at other occasions because of performance reasons. 

For the Overpass /map call (which is in fact only a [shell script wrapper](https://github.com/drolbr/Overpass-API/blob/master/src/cgi-bin/map#L27)), we could think about a global bbox. However, I haven't looked at it in details, i.e. if that would create a different results compared to today's result.

For overpass turbo and the wizard generated queries, maybe adding a global bbox setting would make things much less distracting for most users. @tyrasd : do you think that might be feasible to add?

**Comment by tyrasd** [comment]
yes, using a global bbox for wizard-generated queries makes a lot of sense. I'm currently reworking the wizard code a bit anyway, so it'll be easy to add.

**Comment by mmd-osm** [comment]
@simon04 : I think there's nothing left to do from an Overpass API point of view, hence I suggest to close this ticket. Thanks.

**Comment by simon04** [comment]
Alright, thank you for investigating. @tyrasd would you let the JOSM devs know (create ticket) when the rework is done?

**Comment by tyrasd** [comment]
@simon04 sure thing!
