### ISSUE TITLE
Upstream (OSM) user name changes aren't reflected in results

### ISSUE THREAD

**Issue by mojodna** [drolbr/Overpass-API#257]
This is likely difficult to address in Overpass directly (it's probably related to diff contents), but here goes:
1. A user creates an account on OSM.org with the name "ImAUser". Her user ID is, say, 12.
2. Edits are made.
3. Diffs are transmitted to Overpass.
4. _ImAUser_ later changes her name to "ImReallyAUser".
5. She (or someone else) comes along and re-registers the name "ImAUser" (because it's available) and is assigned user ID 76.
6. User 76 makes edits.
7. Diffs are transmitted to Overpass.

We're encountering this in practice within this bbox: [-80.259418, -3.515306, -80.184231, -3.447453] where the user "Nodes&Roads" appears in the results with 2 separate user IDs (3642735 and 1708958). According to OSM.org, 1708958 is now known as "georhoko", but this has not propagated to Overpass (presumably due to the use of diff updates which do not relay name changes).

We spotted this using Osmosis to create an API DB of the above extract. The Osmosis error is:

```
org.openstreetmap.osmosis.core.OsmosisRuntimeException: Unable to insert user with id 1708958 into the database.
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "users_display_name_idx"
  Detail: Key (display_name)=(Nodes&Roads) already exists.
```

/cc @hallahan

**Comment by mmd-osm** [comment]
I think, there's one important point missing in your example, right after step 4: does user id 12 do further edits after renaming his user to "ImReallyAUser". Only then, this new name would show up in the diff files and Overpass would also update the uid -> username link.

Changing the username on osm.org alone without further edits will never appear in a diff file (!), hence it is technically impossible for Overpass API to reflect that change. So your statement "(presumably due to the use of diff updates which do not relay name changes)" is exactly to the point.

The only reliable means to identify a user in the OSM universe is really the uid. The username can change over time and it is not guaranteed that another cannot take over a given username.

For you queries you could simply use `(uid:3642735)` instead of a user name.

BTW: this affects a lot of other tools as well ...

**Comment by mmd-osm** [comment]
@mojodna : unless you've created some upstream issue to address the underlying issue, I'd suggest to close this issue. As mentioned before, there's nothing which could be done on the Overpass API side as long as the diff files don't include the respective information.

**Comment by mojodna** [comment]
Agreed. Closing.
