### ISSUE TITLE
Overpass does not find places that Nominatim lists and that are shown properly in OSM map

### ISSUE THREAD

**Issue by pmerle** [drolbr/Overpass-API#259]
The following request gives a result of 3 hotels:

http://dev.overpass-api.de/api_drolbr/interpreter?data=[out:json];node[%22tourism%22=%22hotel%22](50.18261441454758%2C-5.501575469970703%2C50.210196900332356%2C-5.44123649597168);out%20body;

but there is at least one hotel, the "Carbis Bay Hotel" missing, which also has the tourism:hotel key set.

Same with cafes: Inside of the same bbox (Carbis Bay, UK) the Beachcomer cafe is not listed when searching for amenity:cafe. The Carbis Bay Holidays building is also missing when searching for building:yes.

Is there a general problem not finding all data, or are there different databases used by Overpass? Or am I doing the wrong queries?

**Comment by pmerle** [comment]
Already found the answer: You've to search for ways and nodes to match all contents.

**Comment by mmd-osm** [comment]
Your query seems incomplete as you're only asking for nodes, rather than
ways and relations as well. That's why some of the hotels are missing.

Please try the wizard in overpass turbo to build a suitable query first.

Btw: any particular reason why you're using the dev instance rather than
one of the production ones?
