### ISSUE TITLE
Translate "Probably the server is overcrowded. " message to English

### ISSUE THREAD

**Issue by SomeoneElseOSM** [drolbr/Overpass-API#291]
I'd suggest instead "The server is too busy at this time".

For info the full text of the error visible to Overpass turbo is:

"An error occured during the execution of the overpass query! This is what overpass API returned:
Error: runtime error: […] Probably the server is overcrowded."

I'm guessing that you might use some translation platform and therefore this issue might best be logged there, but I presume whoever reads this will know what that platform is and will be able to transfer it.

**Comment by drolbr** [comment]
Thank you for the hint. I'm not using a translation platform.

Actually, my first contact with translation platforms is the translation of JOSM into German. While 90% of all entries are correct, about 5% are so profoundly wrong that I turned JOSM to English permanently to avoid translation-back-and-forth headaches. Similar problems exists for the texts of osm.org  although these are translated on a different platform.

The design problem of these translation platform is that they encourage to translate as quick as possible and discourage to dispute poorly translated items, i.e. the feedback channel doesn't work.

On the other hand, you are not the first one who ran into poor English at Overpass API (DaveF did bring up the issue of "attic" on the talk-gb mailing list, which I refuse to change to avoid the homonym with "historic" as in "open historical map"). I suggest the following:

I'll list all the relevant messages from Overpass API in the wiki and give for each a short context. Where native (only British?) English speakers have a better wording, I'll change to that wording.

**Comment by mmd-osm** [comment]
The following list should provide a good starting point, it was created via ` readelf -p .rodata ../cgi-bin/interpreter`:

For technical reasons, some texts span several lines in the table, but are shown as a single message, e.g. 5705 --- 572d. 


Location in file (technical key) | Text
----| -------------
   4|File_Error: 
  11|Unknown attribute "
  25|" in element "
  34|Element "
  3e|" must not contain text.
 190|" cannot be subelement of element "
 1b8|Random_File: bad pos in index file
 1e0|Random_File_Index: Unsupported index file format version
 508|Block_Backend: index out of range.
 530|File_Blocks::read_block: Index inconsistent
 560|For the attribute "ref" of the element "area-query"
 598| the only allowed values are positive integers.
 5c8| appears multiple times at timestamp 
 a38|For the attribute "radius" of the element "around"
 a70| the only allowed values are nonnegative floats.
 aa8|For the attribute "lat" of the element "around"
 ad8| the only allowed values are floats between -90.0 and 90.0 or an empty value.
 b28|For the attribute "lon" of the element "around"
 b58| the only allowed values are floats between -180.0 and 180.0 or an empty value.
 f80|For the attribute "s" of the element "bbox-query"
 fb8| the only allowed values are floats between -90.0 and 90.0.
 ff8|For the attribute "n" of the element "bbox-query"
1030|The value of attribute "n" of the element "bbox-query"
1068| must always be greater or equal than the value of attribute "s".
10b0|For the attribute "w" of the element "bbox-query"
10e8| the only allowed values are floats between -180.0 and 180.0.
1128|For the attribute "e" of the element "bbox-query"
13e0|Bad geometry for way 
1408|The attributes "since" and "until" must be set either both or none.
1450|The attribute "since" must contain a timestamp exactly in the form "yyyy-mm-ddThh:mm:ssZ".
14b0|The attribute "until" must contain a timestamp exactly in the form "yyyy-mm-ddThh:mm:ssZ".
1510| cannot be expanded at timestamp 
1748|"newer" can appear only inside "query" statements.
1a80|A set difference takes exactly two substatements: the set of elements to copy to the result minus the set of elements to leave out in the result.
1da8|For the attribute "type" of the element "id-query"
1de0| the only allowed values are "node", "way", "relation", or "area".
1e28|For the attribute "ref" of the element "id-query"
2261|make-area: Node 
2272| referred by way 
2284| is not contained in set "
22a8| is contained in an odd number of ways.^J
2578|The attribute than must contain a timestamp exactly in the form yyyy-mm-ddThh:mm:ssZ.
2818|<p>Template not found.</p>^J
28c9|<p>No {{node:..}} found in template.</p>^J
28f9|<p>No {{way:..}} found in template.</p>^J
2929|<p>No {{relation:..}} found in template.</p>^J
2958|For the attribute "timeout" of the element "osm-script"
2990|For the attribute "element-limit" of the element "osm-script"
29d0|For the attribute "output" of the element "osm-script"
2a08| the only allowed values are "xml", "json", "csv", "custom", or "popup".
2a58|A bounding box needs four comma separated values.
2a90|Latitudes in bounding boxes must be between -90.0 and 90.0.
2ad0|Longitudes in bounding boxes must be between -180.0 and 180.0.
2b10|The attribute "date" must be empty or contain a timestamp exactly in the form "yyyy-mm-ddThh:mm:ssZ".
2b78|The attribute "from" must be empty or contain a timestamp exactly in the form "yyyy-mm-ddThh:mm:ssZ".
2be0|The only allowed values for "augmented" are an empty value or "deletions".
2c30|The attribute "augmented" can only be set if the attribute "from" is set.
2fc8|For the attribute "bounds" of the element "polygon-query" an even number of float values must be provided.
3038|For the attribute "bounds" of the element "polygon-query" at least 3 lat/lon float value pairs must be provided.
30b0|For the attribute "bounds" of the element "polygon-query" the only allowed values for latitude are floats between -90.0 and 90.0.
3138|For the attribute "bounds" of the element "polygon-query" the only allowed values for longitude are floats between -180.0 and 180.0.
34c0|For the attribute "mode" of the element "print"
34f0| the only allowed values are "ids_only", "skeleton", "body", "tags",  "count", or "meta".
3550|For the attribute "order" of the element "print"
3588| the only allowed values are "id" or "quadtile".
35c0|For the attribute "geometry" of the element "print"
35f8| the only allowed values are "skeleton", "full", "bounds", or "center".
3640|For the attribute "s" of the element "print"
3670|For the attribute "n" of the element "print"
36a0|The value of attribute "n" of the element "print"
36d8|For the attribute "w" of the element "print"
3708|For the attribute "e" of the element "print"
39c7|Invalid regular expression: "
39e8|For the attribute "k" of the element "has-kv"
3a18| the only allowed values are non-empty strings.
3a48|For the attribute "case" of the element "has-kv" the only allowed values are "sensitive" or "ignore".
3ab0|In the element "has-kv" only one of the attributes "k" and "regk" can be nonempty.
3b08|In the element "has-kv" the attribute "regk" must be combined with "regv".
3b58|In the element "has-kv" only one of the attributes "v" and "regv" can be nonempty.
3bb0|In the element "has-kv" regular expressions on keys cannot be combined with negation.
3c08|In the element "has-kv" the attribute "modv" can only be empty or set to "not".
3c58|For the attribute "type" of the element "query"
3c88| the only allowed values are "node", "way", "relation" or "area".
4390|For the attribute "type" of the element "recurse"
43c8| the only allowed values are "relation-relation", "relation-backwards",
4410|"relation-way", "relation-node", "way-node", "way-relation",
4450|"node-relation", "node-way", "down", "down-rel", "up", or "up-rel".
4498|A role can only be specified for values "relation-relation", "relation-backwards",
44f0|"relation-way", "relation-node", "way-relation",
4888|Exactly one of the two attributes "name" and "uid" must be set.
56ab|<p>No results found.</p>^J
5705|Query timed out in "
571a|" at line 
5725| after 
572d| seconds.
5737|Query run out of memory in "
5754| using about 
5762| MB of RAM.
57e0|. Probably the server is overcrowded.^J
5808|. Another request from your IP is still running.^J
5840|Query run out of memory using about 
5868|Query failed with the exception: 
5948|Specify --rules to execute a rule. make-area can only appear in rules.
5990|Couldn't allocate memory for parser.
60f2|CSV format specification
610b|CSV separator character
6207|Unknown query clause
621c|An empty query is not allowed
6268|Invalid UTF-8 character (value below 32) in escape sequence.
62a8|A recursion from type 'w' produces nodes.
62d8|A recursion from type 'bn' produces ways or relations.
6310|A recursion from type 'bw' produces relations.
6340|A recursion from type 'br' produces relations.
6370|CSV output header line (true or false)
6398|Invalid parameter for print: "
63b8|A regular expression for a key can only be combined with a regular expression as value criterion
6420|Nesting of statements limited to 1023 levels
6450|difference takes always two operands
7462|Flushing to database .
7479| done.^J
7481| finished reading relations. 
749f|Update complete.^J
74b1| finished reading nodes. 
74cb| finished reading ways. 
74e4|Reorganizing the database ...
7502|Reading XML file ...
7517| elapsed node 
7526| elapsed way 
7534| elapsed relation 
7550|File error caught: 
75cd|Your input is empty.
75e2|Input too long (length: 
75fb|, max. allowed: 
761b| line(s).
7648|Your input contains only whitespace.
7670|Your input starts with a tag but not the root tag. Thus, a line with the^J
76c0|datatype declaration and a line with the root tag 'osm-script' is^J
7740|Your input contains an 'osm-script' tag. Thus, a line with the^J
7780|datatype declaration is added. This shifts line numbering by 
77e8|No input found from GET method. Trying to retrieve input by POST method.
7838|Only whitespace found from GET method. Trying to retrieve input by POST method.
7888|Found input from GET method. Thus, any input from POST is ignored.
78d0|The server now removes the CGI character escaping.
7908|Parameter "template" must not contain slashes.
7938|The first non-whitespace character is '<'. Thus, your input will be interpreted verbatim.
7998|Parameter "jsonp" must contain only letters, digits, or the underscore.
79e0|Please enter your query and terminate it with CTRL+D.

**Comment by drolbr** [comment]
Please have a look at [http://wiki.openstreetmap.org/wiki/Overpass_API/Wording](http://wiki.openstreetmap.org/wiki/Overpass_API/Wording)

**Comment by drolbr** [comment]
@mmd-osm Sorry, I've already used
```
strip ../cgi-bin/interpreter
strings ../cgi-bin/interpreter | sort | uniq | awk '{ if (length($0) > 12) print; }' | grep -vE '^[0-9][0-9]' | grep -vE '^_' >_
strip ../bin/update_from_dir
strings ../bin/update_from_dir | sort | uniq | awk '{ if (length($0) > 12) print; }' | grep -vE '^[0-9][0-9]' | grep -vE '^_' >>_
cat _ | sort | uniq
```
as a starting point. But feel free to add the missing lines to the above mentioned wiki page.

**Comment by mmd-osm** [comment]
I think most of the suggestions (if not all?) on the wiki page are incorporated in the meantime, see https://github.com/drolbr/Overpass-API/commit/e746a7e7a937fc48c9b89e120c0d12c699569918.

If there's nothing left to do, it's time to close this one.

**Comment by mmd-osm** [comment]
Ping @SomeoneElseOSM : see my comment above. Could you please close this issue? Thanks.

**Comment by SomeoneElseOSM** [comment]
OK
