### ISSUE TITLE
bbox filter on master relations

### ISSUE THREAD

**Issue by mmd-osm** [drolbr/Overpass-API#293]
See [this post](https://help.openstreetmap.org/questions/50752/how-do-i-get-route_master-and-its-children-via-overpass-ql-in-overpass-turbo):

```
  relation["type"="route_master"]["route_master"="bus"](51.3649215, 9.2642212, 51.7134161, 9.810791);
out meta;
```

does not return any result, although (some relation member of) master route https://www.openstreetmap.org/relation/1729861 is included in the bbox.

The wiki page only states: *The bbox-query filter selects all elements within a certain bounding box.* - without providing any more details on the expected behavior.

How is the bbox filter supposed to work with respect to such master relations?
Is this a documentation or implementation issue which needs to  be addressed?

**Comment by drolbr** [comment]
It's on purpose that no relations on relations are found.

There are relations on relations which span to the hundreds of megabytes of data if these were resolved down to nodes. If the semantics of Overpass API required to find such relations then we would have to deal with them in almost each and every query for relations in a bounding box. That make things slow for everybody, those who use rel(bbox) directly and everybody else due to the increased load.
