### ISSUE TITLE
Rate limits seem to be applied after the query is performed

### ISSUE THREAD

**Issue by ezheidtmann** [drolbr/Overpass-API#333]
I'm using the Overpass API and have implemented an exponential backoff when I get a 429 response. But it seems like the requests take just as long for a 200 as for a 429, indicating that the server is performing a query and THEN telling me I'm rate-limited. I would expect that the server would check my rate limit before running the query, avoiding wasting those resources.

If I'm mistaken, then sorry for the noise.

Best,
Evan

**Comment by mmd-osm** [comment]
Please check `/api/status` to get details on your current quota, available slots and minimum wait time before issuing the next requet. Exponential backoff is just a heuristic. Also 429 could be related to your query taking too much time and running in a timeout.

**Comment by ezheidtmann** [comment]
Thanks! I don't think that existed when I first wrote my consumer. Is there documentation on that endpoint?

**Comment by mmd-osm** [comment]
See this post http://listes.openstreetmap.fr/wws/arc/overpass/2016-06/msg00007.html

**Comment by drolbr** [comment]
The exact mechanism is as follows:

After each request the server adds extra time before it admits the next request. The length of the extra time is proportionate to the query's runtime. The factor is the higher the higher the general load is on the server. Otherwise you could block an entire CPU on the server from a single client. That would not be fair to fellow users, and the fair share depends on the number of concurrent fellow users.

A second mechanism that might cause confusion is that the server delays a request up to 15 seconds before it starts if there is not slot available yet. The server counts for the quota only the runtime after the delay. This is to facilitate to fire a bunch of requests asynchronously. If the total load is reasonable, it just works, and you do not need to implement quota management on the client side in that case.
