### ISSUE TITLE
Various comments on `make`

### ISSUE THREAD

**Issue by mmd-osm** [drolbr/Overpass-API#335]
## Add a check for values names:

Example:

```
  make 1;
  out; 
```

Produces invalid XML:

```
  <1 id="1"/>
```

Umlauts: parser error

```
  make ä;
  out;
```
## Endless loop:

```
  make elem a=10^4;
  out; 
```

line 1: parse error: Tag value expected - '^' found.

Similar:

```
  make elem a=10!;
  out; 
```

```
  make elem a=10?;
  out; 
```
## Introduce check for reserved names

```
  make node;
```

This actually conflicts with "reserved" element names such as node, way, relation,
especially as it creates is own id values.

  <node id="1">
    <tag k="key" v="yes"/>
  </node>
## How to modify existing nodes/ways/relations?

Not clear, how to remove tag of original node with while retaining
'node' and all meta data of that node. 

node(3944278427);
make elem ::=u(::),!operator;
out; 

This statement only introduces one new elem node
## Arithmetics

It is even possible to do some basic arithmetics:

```
  make elem sum1=8,sum2=2.5,divisor=1.5,sum=8+2.5,quotient=(8+2.5)/1.5;
  out; 
```

=> Documentation should mention, that also values from inputset can be used:

```
node(307183866);
out;
make bla key = u(asb) + 10;
out;
```
## Mix of "::" and concrete key does not work:

```
node(307183866);
out;

make echo ::="echo:"+u(::)+", again:"+u(asb);
out; 
```

-> Value for key asb is not included in the result.

---
## Alternative inputset handling

"make" sets default inputset as a result, but is unable to consume data from a non-default inputset:

```
node(307183866);
out;

make echo blubb = u(asb);
out;

make echo ::="echo:"+u(::)+", again:"+u(asb);
out; 
```

Question: How to write a query, which would return a result like the following query?

```
node(307183866);
out;

make echo blubb = u(asb);
out;

node(307183866);
make echo ::="echo:"+u(::)+", again:"+u(asb);
out; 
```
## Grouping

The grouping function <em>min</em> and <em>max</em> are most useful on numbers.
If all elements can be interpreted as numbers then the functions compare by number size. 

Q: What happens, if some elements are not numbers? Is everything then treated as string?

```
way({{bbox}})[maxspeed];
  out tags;
  make group min=min(maxspeed), max=max(maxspeed);
  out; 
```

Result:

```
  <group id="1">
    <tag k="min" v="20"/>
    <tag k="max" v="signals"/>
  </group>
```

Is min/max supposed to be numeric only?

**Comment by drolbr** [comment]
Thank you for the feedback. I'll get through the sections one-by-one.

**Comment by drolbr** [comment]
Add a check for values names:

ad "make 1": Thank you for the hint. The parser should give an error on that.

ad "make ä": The XML specification does allow that. However, this would require an overhaul of the parser. On the other hand, I have never seen XML with non-ascii-letter attribute names in practice. And it is not clear if it works with all the other output formats out of the box. Hence, I would keep that with low priority.

**Comment by drolbr** [comment]
Endless loop:

Should be fixed.

**Comment by drolbr** [comment]
Introduce check for reserved names
How to modify existing nodes/ways/relations?

I'm sorry, I need to clarify the documentation. The objects are always immutable, in particular OSM objects. This means that you can have a derived object called "node", "way", or "relation". But it has on purpose no meta information.

The legitimate use case is to create derived data with reworked tags to feed into some tool that expects OSM markup. For this use case, no metadata is needed on the elements. The non-legitimate use case is to use the feature to perform mechanical edits. The absence of metadata will keep Overpass API unsuitable for this, because getting the metadata from somewhere else is as difficult as doing the tag filtering anyway with an external script.

However, tools like JOSM complain on the absence of metadata. Thus, I'm not opposed to add bogus metadata like version=255 for all objects. That would make sense as parameter to print.
It is currently low priority.

**Comment by drolbr** [comment]
Arithmetics

Fixed in the documentation.

**Comment by drolbr** [comment]
Mix of "::" and concrete key does not work:

Thank you for the notification. This should be fixed.

**Comment by drolbr** [comment]
Alternative inputset handling

I'm not sure what you intend here. It is possible to draw from different input sets. The extra tag gets its value from the found relations:
```
node[name="Belsenplatz"];
foreach(
  rel(bn)->.r;
  make node ::=u(::),calling_here=set.r(ref);
  out;
);
```

**Comment by drolbr** [comment]
Grouping

I would like to defer that question. There are different models for this in the wild, e.g. awk and JavaScript have implicit conversions. I hope that people will come up with examples where one or another approach would be preferred and then create an well-defined approach that best serves the users' needs.

**Comment by drolbr** [comment]
Thank you for testing. The test results did give rise to a lot of changes that make the design more consistent. I now close this issue. Still open to do is the documentation, and few people would expect the documentation off this issue.

A short summary of the responses:

"make 1" now produces an error message.

I would like to dismiss having umlauts in element names. I prefer the possibility to treat them as variable names.

The endless loop is fixed, because the whole evaluator parser has been redesigned to be syntax tree based.

In OSM used names are on purpose possible, as explained. In particular, it will not be possible to manipulate tags and keep the meta information. This is to discourage mechanical edits, but to enable people modifying data on the fly.

A proper documentation is still to write, but this should not be buried as a subparagraph in this issue.

The possibility of a generic key has been restricted to the statement convert. The closest equivalent, `convert echo ::="value "+::+", again "+[asb]; out;` does work. It did not make much sense for make anyway. The tests on convert do not indicate any problems so far - further bugs are possible, but unknown.

The "alternative input set" is a matter of documentation. As I have made some changes to the concept, this is still to do (but not inside this issue).

For the precise semantics of min/max I'm grateful for suggestions on the mailing list.
