### ISSUE TITLE
Missing node in JSON output

### ISSUE THREAD

**Issue by dracos** [drolbr/Overpass-API#360]
http://overpass-turbo.eu/s/kZq returns XML for a way including nd 38351777 and that node's co-ordinates in node 38351777, as you would expect. But http://overpass-turbo.eu/s/kZs whilst it includes the node in the list of nodes, does not include an entry for the co-ordinates of the node.

**Comment by mmd-osm** [comment]
Do you happen to check the results via Firefox and CTRL-F? I get some inconsistent search results in Forefox: sometimes Firefox claims to only find one entry in JSON mode. However, if you manually inspect the result, you will see that 38351777 is in fact returned both as part of the way and again as single node. Just copy the result to some other text editor for cross checking.

**Comment by dracos** [comment]
I was looking in both Chrome and Safari with Ctrl-F, yes; I see what you mean when manually looking at the results, apologies for not checking that. I did not realise the "Data" tab did not include the full output.

**Comment by mmd-osm** [comment]
> I did not realise the "Data" tab did not include the full output

It does include everything, but the search is somehow broken.

**Comment by dracos** [comment]
Ah, it looks like the page is only loading some of the data, and then loads more as you scroll through it (and removes it again if you scroll back up), so searching what is currently displayed will not work for that data not yet loaded, which is not made clear.

**Comment by mmd-osm** [comment]
@tyrasd : is this a bug or feature in overpass turbo?

**Comment by tyrasd** [comment]
It's a feature! :shipit: The data tab uses *codemirror* which only displays the lines of text that are actually visible (+- some buffer above and below). This is necessary, because otherwise displaying large results would completely freeze any browser. I think there is some search-plugin for codemirror (similar to what you get when you edit code via the web interface of github), but I'm not sure if integrating that would be very intuitive to use. If you need to actually work with the raw data returned by Overpass API, I'd recommend to just save the data into a file via `Export->raw data`.

**Comment by mmd-osm** [comment]
@tyrasd : great, thanks for background details. Never thought about codemirror in the first place.

@dracos: I guess you can close this issue now, follow up would be in different repo anyway, if needed: https://github.com/tyrasd/overpass-turbo
