### ISSUE TITLE
Augmented diff empty

### ISSUE THREAD

**Issue by geohacker** [drolbr/Overpass-API#365]
Came across a few cases where augmented diff returns no elements: 

* adiff request: https://overpass-api.de/api/interpreter?data=[out:json][adiff:%222017-03-03T08:37:01Z,%22,%222017-03-03T08:37:19Z%22];(node(bbox)(changed);way(bbox)(changed););out%20meta%20geom(bbox);&bbox=46.0502265,35.9096732,54.7044357,47.4171387
* changeset: https://www.openstreetmap.org/changeset/46543036#map=6/42.049/50.482
* achavi: https://overpass-api.de/achavi/?changeset=46543036
* changeset-map: http://osmlab.github.io/changeset-map/#46543036

@mmd-osm @drolbr - could this be because the large relation wasn't processed into augmented diff in Overpass? What should I inspect to understand better? Thank you!

**Comment by mmd-osm** [comment]
You need to tick the relation flag in achavi to see that a tag `name:kn` was added to the relation itself. Otherwise the query will just check for changes in nodes and ways (which there aren't any in this case).

So, there really nothing to do for Overpass API here. Kindly request to close this issue then.

**Comment by geohacker** [comment]
Ah right. I missed that. Thank you @mmd-osm!
