### ISSUE TITLE
How To: systemd for areas daemon

### ISSUE THREAD

**Issue by ChrissW-R1** [drolbr/Overpass-API#387]
Is it possible to define a systemd script for the second dispatcher daemon (areas)?

Specially: How could I terminate the areas session correctly? With dispatcher --terminate only the osm-base process or all dispatcher processes will be killed?
Have I understood that correctly? So how can I only kill the areas dispatcher?

**Comment by mmd-osm** [comment]
I'd recommend to always specify either --osm-base or --areas along with
--terminate. Then it's obvious which dispatcher is getting terminated.

ChrissW-R1 <notifications@github.com> schrieb am Mo. 10. Apr. 2017 um 11:28:

**Comment by ChrissW-R1** [comment]
So it is possible to combine the --terminate parameter with the start ones?
Like **dispatcher --osm-base --terminate**

**Comment by mmd-osm** [comment]
Right. --osm-base just defines the relevant dispatcher, it is not a start
parameter as such.

ChrissW-R1 <notifications@github.com> schrieb am Mo. 10. Apr. 2017 um 11:50:

**Comment by ChrissW-R1** [comment]
Ok, thx. That's what I need.

**Comment by ChrissW-R1** [comment]
Another question about this topic:
Is the order of the process start important? So, does the dispatcher have to start successfully (wait until the output line "Dispatcher just started."), before the rules_loop.sh script should be executed?

Or can I set both commands to one concatenated line in the systemd script?

**Comment by mmd-osm** [comment]
If the dispatcher is not running, osm3s_query in rules_loop.sh will abort with an error message. I'd say you need to make sure that the dispatcher is running before other activities start.

**Comment by ChrissW-R1** [comment]
Do you have any idea, how I could realize this with systemd?
The dispatcher will never stop, only get in a specific status.

**Comment by drolbr** [comment]
The dispatcher comes up within a glimpse of a second. I suggest to delay the start of rules_loop.sh by some seconds.

A more intelligent thing would be to ensure that rules_loop.sh does not start before the updates of the base data have catched up. Generating areas and concurrently updating the base data works, but inflates the size of the database, because we need to keep a snapshot of the data as it were at the start of the loop to assure consistency. But that should be addressed in a separate issue. I suggest to start with the first approach.
