### ISSUE TITLE
Question: Interfacing directly with frontend/dispatcher

### ISSUE THREAD

**Issue by bcspragu** [drolbr/Overpass-API#423]
Hi there,

I know I can execute queries with osm3s_query and with the interpreter, but instead of shelling out to a separate process or using CGI, I was wondering if there's a way to interface directly with the Overpass API, by sending requests directly to the dispatcher? And if there is a way to do it, what protocol does that interface speak?

Context: I'd like to call the Overpass API from within a larger web server, but make the calls in lightweight background green threads, instead of via heavier (osm3s_query/interpreter) processes.

Edit: This should be tagged as a question, but I don't appear to be able to add labels myself.

**Comment by mmd-osm** [comment]
The purpose of the dispatcher process is to coordinate read/writes and global resource management. So you can't really send a query there, as all the logic is in the osm3s_query / interpreter binary respectively.

There's a FastCGI version not yet integrated into mainline, that can serve quite a large number of small requests per second (see chart below) and is fairly lightweight due to caching. Not sure if this would be interesting in your case.

![grafik](https://user-images.githubusercontent.com/5842757/29682589-d6615ffe-890b-11e7-9a81-bff3cca44a64.png)

**Comment by bcspragu** [comment]
I did see the FastCGI branch, which looks very promising!

Depending on the complexity of osm3s_query, I'd be happy to try and make a library for querying a local Overpass API server, though this library would be in Go. Is there any documentation on how osm3s_query works, or a code pointer to what it does to the input query and how it sends it off?

**Comment by mmd-osm** [comment]
osm3s_query (or as CGI: interpreter) really does all the work. There's no concept of "sending the query anywhere else" for further processing. This binary reads an overpass ql or xml query from stdin, parses it, reads all required data from disk, and produces some output on stdout.

There are some projects which created a Python, R, ... wrapper for Overpass API. Effectively that boils down to generating some Overpass QL query and sending the request via HTTP to the interpreter.

**Comment by bcspragu** [comment]
Ah, I understand now. I was imagining the backend/dispatcher like MySQL, listening on a port for queries and responding to them, and the interpreter was just a thin-layer to convert between human-readable Overpass QL and some binary format. Looks like the interpreter is more of a 'thick client'.

**Comment by mmd-osm** [comment]
>  Looks like the interpreter is more of a 'thick client'.

I would probably call it single binary server (from a functional POV).
