### ISSUE TITLE
GeoJSON output

### ISSUE THREAD

**Issue by vassilevsky** [drolbr/Overpass-API#48]
Hello :)

This program can output JSON. That's cool.

But I was wondering why wouldn't it output GeoJSON? It would be even more cool if it could. It would be possible to add Overpass query URLs as GeoJson layers to Leaflet, for example.

Unfortunately, I don't know C++ and cannot derive the answer from the code. I'm sorry.

Thank you.

**Comment by mmd-osm** [comment]
@vassilevsky , @mkoniecz  - is your question answered by @tyrasd comment regarding osmtogeojson?

osmtogeojson is a very mature solution to convert your OSM data to GeoJSON and should be exactly what you're looking for. It is used in overpass turbo, as well as e.g. in QuickOSM (QGIS plugin).

Assuming there's nothing left to do in this ticket, could you please close it? Thank you!

**Comment by mkoniecz** [comment]
@mnd-osm Yes, osmtogeojson turned out to be a suitable tool.

**Comment by stevage** [comment]
I've just come across this issue. My use case is I would like a simple, scriptable way to export some data from the Overpass API to GeoJSON (bicycle route relations in my case).

I see that Overpass Turbo (ie the web interface) supports GeoJSON, but not the API. Which means I can't script it.

Using osmtogeojson or a similar tool is a bit excessive, because that means I need to download an entire extract, even though I only want to use a tiny fraction of the data.

Any other solution that also requires downloading the results of the API, then processing them further into GeoJSON, is also a bit suboptimal because it requires extra intermediate disk space, more tools etc.

So, supporting GeoJSON directly in the API would be valuable (for my use case at least).

(I do understand the semantic difficulties around converting OSM data to GeoJSON. Doing whatever Overpass Turbo is doing would seem like a pretty reasonably start.)

**Comment by mmd-osm** [comment]
@dktue : your comment is somewhat unspecific and not actionable. Besides adding comments to a closed issue is not recommended, as noone will look after it. Can you add a detailed use case, where existing tools won't do?

**Comment by mmd-osm** [comment]
Seems like you're already using Leaflet, so why not add https://github.com/openstreetmap/leaflet-osm as a plugin and request data from Overpass API in XML format? Or use https://github.com/GuillaumeAmat/leaflet-overpass-layer maybe.

**Comment by dktue** [comment]
The display_map-plugin doesn't support this at the moment. Somebody will have to code: Either the maintainer of the mediawiki-display_map-plugin or the overpass-maintainer.
