### ISSUE TITLE
Cannot query areas on local installation. 

### ISSUE THREAD

**Issue by aaguerreberre** [drolbr/Overpass-API#546]
Hello, 
We have a local installation of the latest OverPass API version using the GeoFabrik file for Mexico: 

https://download.geofabrik.de/north-america/mexico-latest.osm.pbf

All queries involving node, way and relation work just fine. However, when we try to invoke queries using "area", this error comes up: 

`Error: runtime error: The dispatcher (i.e. the database management system) is turned off.`

It seems that at the file system level, the area files are not being generated. However, when dumping the OSM file to a database, we can see there are areas defined. 

Is there any flag we're missing on our OVP database generation? Or is there any issue with the GeoFabrik files? 

Thanks a lot in advance!

**Comment by mmd-osm** [comment]
See https://gis.stackexchange.com/questions/342712/data-imported-into-overpass-api-lacks-areas-bin

**Comment by aaguerreberre** [comment]
Amazing, we'll take a look and let you know!

Thank you so much for the quick response!

**Comment by mmd-osm** [comment]
Ok, if this issue is solved and there are no more questions, can you please close it?

Also note that this issue tracker is mainly used for *bug reports*  and *enhancement requests*. If you have general questions, better use one of the sites mentioned on the wiki page:

* https://wiki.openstreetmap.org/wiki/Overpass_API#Community:_where_can_I_get_help.3F
* https://wiki.openstreetmap.org/wiki/Overpass_API#Developers_.2F_System_Administrators
