### ISSUE TITLE
HTTP status codes

### ISSUE THREAD

**Issue by drolbr** [drolbr/Overpass-API#56]
Reminder to self: Check that as much runtime errors as possible get HTTP code 503 instead of HTTP 200.

**Comment by drolbr** [comment]
Done since quite some time. It is actually HTTP 504 and HTTP 429.

**Comment by mmd-osm** [comment]
In case the dispatcher is not running, we should not return HTTP 200 along with a remark "Error: runtime error: open64: 2 No such file or directory /osm3s_v0.7.54_osm_base Dispatcher_Client::1".

Better would be something like 500, so that tools like fail2ban can automatically blocks buggy clients that keep on flooding the server with requests.
