### ISSUE TITLE
Как унаследовать, адрес для подъезда или POI, если он проставлен на контуре дома?

### ISSUE THREAD

**Issue by Sowa1980** [drolbr/Overpass-API#612]
Как унаследовать, адрес для подъезда или POI, если он проставлен на контуре дома?
Подскажите , как это сделать через http://overpass-turbo.eu/
То есть, адрес проставлен на домах, а на подъезда или POI,, он отсутствует.
в формате .csv

**Comment by mmd-osm** [comment]
deepl translation:

How do I inherit an address for a porch or POI if it is stamped on the outline of a house?
Can you tell me how to do this via http://overpass-turbo.eu/?
That is, the address is stamped on the houses, but not on the porches or POIs.

Answer:

(deepl translation)
На данный момент это не поддерживается, потому что мы пока не можем выяснить, находится ли POI внутри здания.
Дубликат #77

This is not supported at the moment, because we cannot  yet find out, if a POI is inside a building.

Duplicate of #77

**Comment by Sowa1980** [comment]
Если я вас правильно понял, то унаследовать адресную информация по полигону Административного деления (administrative, place=suburb и так далее)  , для зданий тоже не получится?

**Comment by mmd-osm** [comment]
(deepl automated translation)
То, что вы описываете, звучит очень похоже на геокодирование: у вас уже есть некоторые POI и вы хотите обогатить их дополнительной информацией из вашей административной границы, или некоторой адресной информацией из окружающего здания. Overpass API не является хорошим инструментом для выполнения этой задачи, вместо этого вам стоит обратить внимание на специальных геокодеров, таких как [Nominatim](https://wiki.openstreetmap.org/wiki/Nominatim). Они как раз и сделаны для этого случая использования, и вы получите гораздо лучшие результаты, чем при использовании overpass.

Переведено с помощью www.DeepL.com/Translator (бесплатная версия)


Original text:

What you describe sounds very much like geocoding: you already have some POI and want to enrich it with additional information from your administrative boundary, or some address information from a surrounding building. Overpass API is not a good tool for this task, you should look at dedicated geocoders instead, such as Nominatim. They are exactly made for this use case and you will get much better results than with overpass.

**Comment by drolbr** [comment]
@mmd-osm Thank you for answering the questions.
