### ISSUE TITLE
Inconsistent error messages among output types

### ISSUE THREAD

**Issue by Mashin6** [drolbr/Overpass-API#620]
Currently when something goes wrong with a query the api responds in different way depending on which out: type was selected.

1. when syntax error or bbox out of range fails silently (csv, json, xml)
2. when query ran and timed out returns only header (csv)
3. When no slots available and query times out while waiting in the queue fails silently (csv, json, xml)

Particularly problematic is csv because it gives no error messages at all.

**Comment by drolbr** [comment]
A syntax error should result in a HTTP 400 Bad Request. I do not understand what you mean by "bbox out of range".
A timeout is indeed not signalled in csv, because there is no obvious place for error messages in csv.
Load shedding is indicated by HTTP 504 if the server is overloaded or HTTP 429 if the server had seen too many requests from the IP address. Please see [the user's manual](https://dev.overpass-api.de/overpass-doc/en/preface/commons.html).
