### ISSUE TITLE
node(r) recursion problem?

### ISSUE THREAD

**Issue by DaveF63** [drolbr/Overpass-API#646]
Is there a reason this returns 'intentionally blank' instead of nodes. I've received the same for a few, different relations
```
rel(7149329);
node(r);
out center;
```

This returns the expected nodes:
```
rel(7149329);
way(r);
node(w);
out center;
```

https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Recurse_.28n.2C_w.2C_r.2C_bn.2C_bw.2C_br.29

**Comment by mmd-osm** [comment]
According to the documentation you've cited: `node(r); ` would "select node members of relations in the input set"

Now, because [relation 7149329](https://www.openstreetmap.org/relation/7149329) only has 2 way members and no node members, the first query won't return anything. 

Important point here is that nodes which are part of the way are not members of the relation itself.

**Comment by DaveF63** [comment]
Understand. Thanks.
