### ISSUE TITLE
Adminstrative relation not found inside its parent area

### ISSUE THREAD

**Issue by Szetty** [drolbr/Overpass-API#669]
Hello, we have a query, where we want to find all administrative relations inside another administrative relation. I have used a query where I search the parent relation by id, map it to an area, and then search for all relations that are administrative inside this area. This query has been working for 99% of the cases, but I have found one exception: https://www.openstreetmap.org/relation/2785126. For some reason I cannot find this relation inside its administrative relation.
I have two examples:
 1. https://postimg.cc/ph8gCz5J with query "[out:json];area(3602955436);node(area);out;"
 2. https://postimg.cc/zL4sT0vf with query "[out:json];area(3602955436);rel(area)[admin_level];way(r);node(w);out;"

In 1 I am querying for all the nodes inside the parent area, and as we can see all nodes are returned. In 2 I am querying for all the adminstrative relations inside the parent area and then for their ways and nodes of the ways, which will give me the boundaries of the relations. As you can see only 2/3 relations are outlined by the nodes.

Any idea what might be the problem ?

**Comment by mmd-osm** [comment]
By construction, the outer boundary of your area is not part of the area itself. If the relation shares the all ways with the area relation and doesn't have any nodes inside the area, it won't be considered to be inside the relation.

**Comment by Szetty** [comment]
what do you mean by doesn't have any nodes inside the area ? on the first image you can see that there are a ton of points even inside the area that are also part of the parent area

**Comment by mmd-osm** [comment]
What I mean is that none of the relations you're looking has any node members (such as an admin_centre), or any way members, which are not exactly matching your existing area.

**Comment by drolbr** [comment]
Relation 2785126 is not inside the area spanned by relation 2955436 because there is no point of relation 2785126 that is properly inside relation 2955436.

Overpass API treats relation 2785126 based on its way and node members and is not aware that it is a closed area. As such relation 2785126 is relative to relation 2955436 similar to relation 1683644. Both share a part of their boundary with relation 2785126 but have no points inside. For sure, relation 1683644 is not expected to be in the result.

The source of the problem is that there is no proper area type in the OSM data model. On top of that, there is no area-in-area operator in Overpass API at the moment.

**Comment by Szetty** [comment]
Would the problem be solved if I add an admin_centre (for example the node 240044253) in 2785126 ?

**Comment by drolbr** [comment]
For this relation, yes.
