### ISSUE TITLE
Timeline misses versions with same timestamp

### ISSUE THREAD

**Issue by nrenner** [drolbr/Overpass-API#686]
Versions 3 and 4 of [node ‪3202699546‬ (history)](https://www.openstreetmap.org/node/3202699546/history) share the same timestamp `2021-12-16T16:01:38Z`, see also [History Browser](https://osm.virtuelle-loipe.de/history/?type=node&ref=3202699546), [API](https://www.openstreetmap.org/api/0.6/node/3202699546/history).

A `timeline` query for version 3 does not return a result:

```
[out:csv(refversion, created)];
timeline(node, 3202699546, 3);
out;
```
https://overpass-turbo.eu/s/1tcO

```
Actual                               Expected

refversion  created                  refversion  created             
                                     3           2021-12-16T16:01:38Z
```

Iterating over all versions also misses version 3:

```
[out:csv(refversion, created)];
timeline(node, 3202699546);
out;
```
https://overpass-turbo.eu/s/1tcR

```
Actual                               Expected

refversion  created                  refversion  created
1           2014-11-24T08:29:08Z     1           2014-11-24T08:29:08Z
2           2021-12-07T08:17:41Z     2           2021-12-07T08:17:41Z
                                     3           2021-12-16T16:01:38Z
4           2021-12-16T16:01:38Z     4           2021-12-16T16:01:38Z
```

**Comment by drolbr** [comment]
This is the intended behaviour. To make sense of the OSM data and its oddities, in particular the way coordinates in OpenStreetMap, one must define precise model assumptions.

Overpass API relies on the timestamps of the objects, in particular to resolve way coordinates. This avoids to have to deal with states that existed only after a minute diff on the replicated side because an object update appears in the minute updates later than it was performed on the primary database server (up to 20 minutes delay have been observed).

This also means that object versions with zero lifetime do not exist in the Overpass API model. In all investigated cases where two versions of the same object and same timestamp exist, they have the exact same data. So there is no information loss.

**Comment by mmd-osm** [comment]
> In all investigated cases where two versions of the same object and same timestamp exist, they have the exact same data

I doubt this is correct. Let's take one concrete example I just found in the log files:

```
Version 15 has a later or equal timestamp (2023-04-02T18:25:50Z) than version 16 (2023-04-02T18:25:50Z) of Way 26434131
Version 16 has a later or equal timestamp (2023-04-02T18:25:50Z) than version 17 (2023-04-02T18:25:50Z) of Way 26434131
```

As we can see in the OSM Deep History for this way, tagging differs across object versions: https://osmlab.github.io/osm-deep-history/#/way/26434131 

![image](https://user-images.githubusercontent.com/5842757/229377416-4ac965f3-0fa3-4702-9394-5bc8bae11d51.png)

Similar effects of course also apply to nodes, and to a much lesser extent also relations:

```
Version 12 has a later or equal timestamp (2023-04-02T15:42:07Z) than version 13 (2023-04-02T15:42:07Z) of Node 2125500002
Version 13 has a later or equal timestamp (2023-04-02T15:42:07Z) than version 14 (2023-04-02T15:42:07Z) of Node 2125500002
```


StreetComplete is pretty famous for this kind of behavior. I reported it 2 years ago already: https://github.com/streetcomplete/StreetComplete/issues/2318#issuecomment-868975126

Now that the API is much faster than pre-2019 (thanks to CGImap), we're seeing these effects much more frequently nowadays in Overpass API.

**Comment by mmd-osm** [comment]
@nrenner : if you feel strongly about this, you could try to reach out to StreetComplete and discuss with them, if they could introduce some additional delay of 1s between uploads for the same object ids. I wanted to propose something similar in the past, but it didn't seem like a huge issue. YMMV.

**Comment by nrenner** [comment]
@mmd-osm StreetComplete does unusual things, but nothing wrong, so downstream tools just have to deal with it. OSMCha could request those edge cases from the OSM API, but that would be yet another workaround for a workaround.

**Comment by mmd-osm** [comment]
The easiest way would probably be to introduce some rate limiting for the API upload endpoint (+ single object create/update/delete). Nominatim already has a limit of 1 request/s, as defined in the Nominatim usage policy.

Since this would result in a massive slow down for people uploading one object at a time, I have some doubts anyone would be willing to implement such rate limiting. Still, I would assume most users wouldn't notice it at all.

**Comment by mmd-osm** [comment]
> Since this would result in a massive slow down for people uploading one object at a time

Now that this getting worse (e.g. https://www.openstreetmap.org/api/0.6/way/1180426639/history), it's time to double check this assumption. I think it would be sufficient to check when an object version was last updated, and if that's less than a second (or some configurable parameter in milliseconds), the OSM API could simply wait a bit. Most likely,  StreetComplete would be the only app that's slowed down a bit by such a change.
