### ISSUE TITLE
user_touched not working as expected

### ISSUE THREAD

**Issue by dieterdreist** [drolbr/Overpass-API#722]
I am not sure if "user_touched" is expected to work and what it does exactly (because I couldn't find it in the osm wiki docs), but I thought it would select everything ever touched by the user, because for the last modifying user there is already `user`.

### What I did:
This is my query:
```
[out:json][timeout:125];
// gather results

way(user_touched:"dieterdreist")({{bbox}});
// print results
out geom;

```

### What I got:
![Screenshot 2024-04-23 at 11 38 26](https://github.com/drolbr/Overpass-API/assets/581288/a6ab1667-789f-4507-a24a-f2bd23d74fcd)

### What is missing:
There is for example this way, in the above screenshot located in the bottom to the right, close to the label "Venezia", which is this OSM object, created by dieterdreist and later also modified by dieterdreist, which doesn't show up: https://www.openstreetmap.org/way/32454740/history

**Comment by mmd-osm** [comment]
If you look at the timestamps for way 32454740, all of your changes happened before September 2012, which is when the first ODbL compliant planet was released. Overpass doesn't know about your changes, if they happened before that cut off date.

This behavior is by design and expected as is. It's not a bug.

**Comment by mmd-osm** [comment]
If you look at the timestamps for way 32454740, all of your changes happened before September 2012, which is when the first ODbL compliant planet was released. Overpass doesn't know about your changes, if they happened before that cut off date and you were not the last one to modify the way when first ODbL planet file was released.

This behavior is by design and expected as is. It's not a bug.

**Comment by dieterdreist** [comment]
thank you for the explanation
