### ISSUE TITLE
Invalid `latest_dir` `2024-05-20` points on directory which doesn't exists

### ISSUE THREAD

**Issue by scorsi** [drolbr/Overpass-API#728]
Hello,
I don't know where to post for that,
but the `latest_dir` in https://dev.overpass-api.de/clone/ points to `2024-05-20` instead of `2024-05-22` which causes failures on cloning because the directory doesn't exists.

**Comment by scorsi** [comment]
It got fixed yesterday.

**Comment by mmd-osm** [comment]
It got updated with the new date 2024-05-22 once the clone process has finished, but there's still some issue here.

**Comment by drolbr** [comment]
Thank you for reporting the problem. The underlying root cause is that the hard disk of dev.overpass-api.de got very slow (around 5-10 MB/s) over time and needs a replacement.

There have been considerations to move clone generation to a different machine which should have combined virtualization with Ansible, and various people did disagree how to do that in the right way. As a mitigation the clone generation has been reduced from daily to three times a week some time ago, and I will transition to twice a week now to give the slowing hard disk more time.

Another mitigation is to replicate as many files as possible client side. There is a partial implementation for the next release, but it has not been tested so far.

All in all, I'll leave this open as a task to ensure it can be tacked when one of the approaches to
- reduce the amount of data to transmit
- move to a new server
has come to fruition.
